### ISSUE TITLE
tip

### ISSUE THREAD

**Issue by GZA1** [LuisBurgos/design-patterns#1]
hey! me fue de gran ayuda para repasar los patrones, un consejo, concrete es cemento en ingles jajaja, pero buen trabajo tio

**Comment by luisburgos** [comment]
Hola @Khalifa96, muchas gracias por el feedback, super cool que te haya sido de ayuda 👍 

Respecto a lo del concreto, si nos vamos a la traducción literal, estás en lo correcto 🙈 

Sin embargo, la construcción de las clases e interfaces del repo están orientadas a un contexto en inglés, por ejemplo, podemos hacer una búsqueda en Google como: `concrete implementation of interface java` nos arroja resultados en el contexto usando ese término.

Un saludo!
